### ISSUE TITLE
Configuration help

### ISSUE THREAD

**Issue by svalavuo** [OpossumGit/LastNightscout#1]
Hi,

I just got a Pebble from my co-worker and installed LastNightscout.
I can't get it to work though. :(
I made a new token to my (self hosted) Nightscout -site (readable -profile) and typed that url (with token) to LastNightscout settings. My Pebble only shows clock and blank screen.
What did I do wrong?
This seems to be the only Pebble app that shows you the current values, others seems to be only for data input.

thanks,
- Samuli

**Comment by OpossumGit** [comment]
Hi,
This watchface gathers data from following uri:
[config_uri]/api/v1/entries/sgv.json 
where [config_uri] is whatever you write in the settings. 
It was not designed with security profile tokens in mind. I assume that you append token inside [config_uri] part. I guess natural position for token should be at the end (after sgv.json) which is non existing feature

Make sure that your sgv.json is available publicly (no tokens) from your mobile phone and it should work. That means that you must be able to load (tokenless) uri in browser of the phone that is paired with Pebble). 

Also, my Pebble broke and I do not have one anymore to test. I know Pebble was closing servers (or they already did) and I am not sure whether that could affect watchface. Watchface itself is not dependent of Pebble services but I do not know how does Pebble mobile app behave after shutdown, as it is the one that does the communications to the uri. 

Good luck

**Comment by OpossumGit** [comment]
Also, you say that you can’t find watchfaces displaying data. Have you tried ones from list on this site:
http://www.nightscout.info/wiki/cgm-watchfaces

Not sure how to download them though, if servers are down.

**Comment by svalavuo** [comment]
Hi,

Can't find them from https://apps.rebble.io :(
I'll try to figure out the way to access my site without token. Thanks!

- Samuli

**Comment by svalavuo** [comment]
Just tested that your hypothesis and you are right.
[config_uri]/api/v1/entries/sgv.json should be 
[config_uri]/api/v1/entries/sgv.json?[token] for that to work.

- Samuli
